server:
  port: 8080
  servlet:
    context-path: /whatsapp

spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/whatsapp?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 6000ms

jwt:
  signerKey: "b2yoP+BXkNpTkT3UA7TSAHxqoLxuzgZIRmscynx2zbm5PHbtt3U+JB5N1G6AIrNg"
  valid-duration: 3600
  refreshable-duration: 7200